### ISSUE TITLE
White space below footer

### ISSUE THREAD

**Issue by ethanmad** [key-amb/hugo-theme-bootie-docs#16]
As you can see in [this screenshot](https://ptpb.pw/g7J1.png), there is extra white space below the footer. I get this in Chrome desktop (Linux) and mobile (Android).

I have the same problem in my fork of bootie-docs, [UM-Fencing/club-theme](https://github.com/UM-Fencing/club-theme), which you can see live at http://umich.edu/~fencing.

I don't see anything in the HTML or CSS that would cause this extra space and it's bothering me.
Any ideas to eliminate it?

**Comment by key-amb** [comment]
Hello.

Thank you for your report.
I see same white space too on my site using this theme.

I think this is from `padding-bottom: 30px;` style specified here: https://github.com/key-amb/hugo-theme-bootie-docs/blob/v1.1.1/static/css/theme.css#L3

I'll check if I can remove this.
