### ISSUE TITLE
Hugo 1.8 breaks header.html partial menu logic

### ISSUE THREAD

**Issue by ethanmad** [key-amb/hugo-theme-bootie-docs#18]
Everything worked perfectly with Hugo versions <= 1.7, but the menu does not populate anymore.

Everything from [hugo-theme-bootie-docs/layouts/partials/header.html line 36](https://github.com/key-amb/hugo-theme-bootie-docs/blob/master/layouts/partials/header.html#L36) to line 52 appears to now be broken under Hugo 1.8.

My theme is [similar enough](https://github.com/UM-Fencing/club-theme/blob/master/layouts/partials/header.html) and experiences this [problem](https://ptpb.pw/KNPD.png), too. In my site's config.toml, I have defined [`noCategoryLink`](https://github.com/UM-Fencing/UMFC-website/blob/master/config.toml#L8) and have a [`mainMenu`](https://github.com/UM-Fencing/UMFC-website/blob/master/config.toml#L39) array, yet now I get only a 'Home' and a 'Categories' link in the menu. (I want all of the pages defined in the `params.mainMenu` to show up and I don't want `Categories`.)

If you build your site with the latest version of Hugo, you should also experience this 

I'm not sure which change in Hugo 1.8 ([changelog](https://github.com/spf13/hugo/releases/tag/v0.18)) caused this problem, but I'd be happy to work on this with you.

**Comment by key-amb** [comment]
Thank you for your report.
Though I'm not sure about what causes this, I'll check it soon.

**Comment by key-amb** [comment]
I confirmed this problem.

Hugo changed its behavior at v0.18 https://github.com/spf13/hugo/releases/tag/v0.18

Here they say:

> All the Params configurations are now case insensitive #1129 #2590 #2615

And [the document on gohugo.io](https://gohugo.io/templates/variables/) says now:

> All Params are only accessible using all lowercase characters.

So it seems that we have to change all variables in config.toml into lowercase.
I'll do this.

**Comment by ethanmad** [comment]
This seems like a bug in Hugo, doesn't it? The conflicting information and
results is confusing, at least.

**Comment by key-amb** [comment]
Oh, I misunderstood one thing.
bep fixed this problem by https://github.com/spf13/hugo/pull/2717

And we can access by `{{ .Site.Params.mainMenu }}` instead of `{{ .Site.Params "mainMenu" }}` .

So we don't need to change config variables into lowercase. Just do above.
I'll do this.

Thanks,

**Comment by key-amb** [comment]
I opened a topic in Hugo's discussion forum: https://discuss.gohugo.io/t/config-params-should-be-all-lowercase-or-not/5051/1 to ask a recommended way to solve this problem just in case.

**Comment by ethanmad** [comment]
I guess we found a bug in Hugo together! Thanks for doing the research and posting on the discussion forum.

**Comment by ethanmad** [comment]
Upstream issue: https://github.com/spf13/hugo/issues/2907.
