### ISSUE TITLE
$isHomePage broken by Hugo 1.8

### ISSUE THREAD

**Issue by ethanmad** [key-amb/hugo-theme-bootie-docs#20]
Since the home page is just a normal page now, comparing titles is broken (since the home page's title is "_index").

There is now page variable to determine if this page is the home page, .IsHome (see https://gohugo.io/templates/variables#page-variables), which works well. I'm making changes in my theme which I will share with you when I have finished them.

**Comment by ethanmad** [comment]
Check out https://github.com/UM-Fencing/club-theme/commit/c85f84853e1f4d18a6935b43d989dc031b56e76e.

The changes to `header.html` should be compatible, but bootie-docs doesn't have the other two partials I made changes to.

**Comment by key-amb** [comment]
@ethanmad 

Thank you for your reporting.
It's true title handling is failing at http://key-amb.github.io/bootie-docs-demo/ , too.

I'll check the information above and do what to be done.
Maybe we should change `min_version` of this theme which is `0.14` currently.

**Comment by ethanmad** [comment]
@key-amb Just apply changes similarly to how I did in UM-Fencing/club-theme@c85f848. You can probably do it all using sed or find-and-replace and then add in the logic clean-ups by hand.

(By the way, you'll notice from my changes that `{{ if variable }}` works the same as `{{ if eq variable true }}`, just like in C: `if (variable)` is equivalent to `if (variable == true)`). 

If only my fork had not diverged so much from yours, I could have submitted a PR for you to merge with one click.


This breaks backward compatibility with [Hugo versions less than v0.15](https://github.com/spf13/hugo/commit/be535832f7f4889351df84bad5059bae4db5a95d).
