### ISSUE TITLE
Repository transfer to @progrhyme

### ISSUE THREAD

**Issue by key-amb** [key-amb/hugo-theme-bootie-docs#30]
To whom it may concern,

I'm going to transfer this repository to @progrhyme who is my new account along with [the demo repository](https://github.com/key-amb/bootie-docs-demo).

Things to be done:

- [x] Update [gohugoio/hugoThemes](https://github.com/gohugoio/hugoThemes) after the transfer
  - https://github.com/gohugoio/hugoThemes/pull/280

I don't anticipate any big trouble with this. GitHub automatically redirects accesses to old URLs to new ones.
But please take care just in case.

If you are unfamiliar with _repository transfers on GitHub_, [the official document](https://help.github.com/articles/about-repository-transfers/) may be helpful.

I will execute this transfer in a few days.

Thanks,

**Comment by progrhyme** [comment]
Completed.
