### ISSUE TITLE
Images missing max-width property

### ISSUE THREAD

**Issue by paskal** [key-amb/hugo-theme-bootie-docs#33]
Hello!

Thank you for very nice theme! I've stumbled on issue exactly the same as reported https://github.com/dim0627/hugo_theme_beg/issues/19:
![image](https://user-images.githubusercontent.com/712534/37655447-62930728-2c56-11e8-8e12-2079fa34f05e.png)

**Comment by progrhyme** [comment]
Thank you for your reporting.

I've roughly gone through the original issue.

I'll try to fix this later.
