### ISSUE TITLE
Example Demo Site Not included

### ISSUE THREAD

**Issue by washere** [key-amb/hugo-theme-bootie-docs#36]
Hi,

I really like this theme. 

Most themes include their Demo website.

Can we have the zip file for the demo:

https://themes.gohugo.io/theme/bootie-docs/

Uploaded to github or elsewhere (zippyshare.com, mediafire.com) so we can learn this theme?

It will be a great tool to spread the use of this theme.

Best way to learn the specifications for a theme is to play with a demo site.

Please upload the demo site as a zip.

Thanks again.

**Comment by progrhyme** [comment]
Thank you for your suggestion.
I split the demo site repository into here: https://github.com/progrhyme/bootie-docs-demo/ .

It's a shame that [the demo site](https://progrhy.me/bootie-docs-demo/) has mixed-contents problem now.
I will work with this soon.

**Comment by progrhyme** [comment]
Fixed the mixed-content problem. https://github.com/progrhyme/bootie-docs-demo/commit/e0df59934417a5b18bde5e186c9761996c1d7990
